### ISSUE TITLE
getGraphicsEvent on Mac

### ISSUE THREAD

**Issue by mdsumner** [SWotherspoon/SGAT#5]
We've seen this: 

```R
# http://ornithologyexchange.org/forums/topic/28015-bastag-flightr-mac-osx/
wl<-preprocessLight(d.lux, threshold, offset = offset,lmax=12)
 
Error in setGraphicsEventEnv(which, as.environment(list(...))) : 
  this graphics device does not support event handling
 
# I am using Mac OS X 10.11.3 El Capitan, R version 3.2.4 Very Secure Dishes
```

Workaround is

```R
# try opening the graphics window first with
X11(type = "Xlib")
```

**Comment by mdsumner** [comment]
wrong package

**Comment by abfleishman** [comment]
I am having this problem too and the workaround opens a ew graphics window but when I run the function it opens a new window and throws the error.

**Comment by abfleishman** [comment]
I found your TwGeos package which has a function of the same name that has an argument `gr.Device = "x11"` for use on a mac and it seems to work.

**Comment by J-Cleeland** [comment]
Hey @mdsumner 

I've tried all the suggestions above and more. I'm having exactly the same issue as abfleishman. It will open a second window with light profile however it is not interactive. I'm on OS x and not sure of the next step. Want to avoid sourcing a PC before I am shipbound next week.

![screen shot 2017-09-02 at 3 46 23 am](https://user-images.githubusercontent.com/5497888/29981569-70ef1f4e-8f91-11e7-92a4-b17d104f1000.png)
![screen shot 2017-09-02 at 3 45 25 am](https://user-images.githubusercontent.com/5497888/29981570-70f050b2-8f91-11e7-8e65-e5e147795b3b.png)

**Comment by slisovski** [comment]
Try install:

slisovski/TwGeos

The function preprocessLight has the option to choose "x11" for macs!

The package got some extras but it's entirely based on BASTags

Cheers
Simeon

**Comment by slisovski** [comment]
I forgot - you need to install X11 first!

**Comment by J-Cleeland** [comment]
Hi @slisovski.

I've had a go with TwGeos::preprocessLight. It allows me to interact with left and right mouse clicks in the Edit Window. But I don't have a second window and am not getting a response from "q" and "a" keys. I've tried opening two X11 windows, but I'm not having any such luck with it.

**Comment by slisovski** [comment]
That's weird - have you specified "x11" in the arguments?? See ?preprocessLight (sorry if you have studied that already)... works fine on my macs!

**Comment by J-Cleeland** [comment]
Hi @slisovski,

I've reinstalled X11 and got it working. However, when I flick through the individual twilights the window flashes between each twilight and the complete light profile...in a strobe light fashion. I suspect this isn't normal and there is something wrong with how X11 is being called...as I still don't have two windows. It looks like it is trying to run everything through a single window which is causing a flickering effect. I'll dig a little deeper and get back to you if I have any success. Jaimie
