### ISSUE TITLE
sstLogp (and others) error caused by update to raster::shift

### ISSUE THREAD

**Issue by J-Cleeland** [SWotherspoon/SGAT#8]
Multiple SGAT functions produce error:

> Error in (function (classes, fdef, mtable)  :  unable to find an inherited method for function ‘shift’ for signature ‘"numeric"’

Seems like the cause is an update to the format of arguments in raster::shift??

@mdsumner @SWotherspoon

**Comment by mdsumner** [comment]
yes that's it, protest was registered: https://github.com/rspatial/raster/issues/66

nothing we can do but update SGAT

**Comment by J-Cleeland** [comment]
Any work around because its pretty inconvenient? Use older version of raster I suppose??

**Comment by mdsumner** [comment]
hang on

**Comment by mdsumner** [comment]
actually, are you sure this is in SGAT itself? It would be in `land.mask()` but that's commented out, any chance it's in a local file?

**Comment by J-Cleeland** [comment]
sstLogp

**Comment by J-Cleeland** [comment]
Just for those with the same issue - sstLogp works fine. If you are using the land/sea mask (SST.r) this script calls raster::shift multiple times - because of the change to the format of the shift arguments you will need to update the script.
